site_name: "THE QUANTUM OPERATOR'S GRIMOIRE: A First-Principles Manual for Reality Hacking"
theme:
  name: "material"
nav:
  - The Grimoire: index.md
  - About: about.md
  - License: license_page.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols

plugins:
  - search
